/** Ana Farma V2 HTTP boundary: canonical schema only, read-only until persistence gate passes. */
function doGet(e){try{return afJson_(afDispatchGet_(String((e&&e.parameter&&e.parameter.action)||'health')));}catch(error){return afError_(error);}}
function doPost(e){try{const body=afParseBody_(e),action=String(body.action||'');if(action==='health')return afJson_(afHealth_());if(action==='getSellableCatalog')return afJson_(afGetSellableCatalog_());if(action==='getOpenShift')return afJson_(afGetOpenShift_());if(action==='createTransaksiV2')throw afHttpError_('TRANSACTION_API_NOT_ENABLED','V2 transaction mutation is not enabled until the live persistence integration gate passes.');throw afHttpError_('UNKNOWN_ACTION','Unknown V2 action: '+(action||'(empty)'));}catch(error){return afError_(error);}}
function afDispatchGet_(action){if(action==='health')return afHealth_();if(action==='getSellableCatalog')return afGetSellableCatalog_();if(action==='getOpenShift')return afGetOpenShift_();throw afHttpError_('UNKNOWN_ACTION','Unknown V2 action: '+(action||'(empty)'));}
function afHealth_(){const ss=afV2Spreadsheet_();return{success:true,service:'ana-farma-v2',status:'READY_READ_ONLY',schemaVersion:AF_V2.schemaVersion,spreadsheetId:ss.getId(),spreadsheetName:ss.getName(),timestamp:new Date().toISOString()};}
function afGetSellableCatalog_(){
  const actor=afCurrentActor_('SELL'),ss=afV2Spreadsheet_(),products=afRows_(ss,'Product'),units=afRows_(ss,'ProductUnit'),prices=afRows_(ss,'ProductPrice'),balances=afRows_(ss,'StockBalance'),now=new Date(),stock={};
  balances.forEach(r=>{if(String(r.productId||'').trim())stock[String(r.productId)]=Number(r.quantityBase||0);});
  const byProduct={};products.forEach(p=>{if(afBool_(p.active))byProduct[String(p.productId)]=p;});
  const unitsByProduct={};units.forEach(u=>{if(afBool_(u.active)&&String(u.productId||'').trim()){const id=String(u.productId);(unitsByProduct[id]||(unitsByProduct[id]=[])).push(u);}});
  const activePrices={};prices.forEach(p=>{if(!afBool_(p.active))return;const from=p.effectiveFrom?new Date(p.effectiveFrom):new Date('1970-01-01T00:00:00Z'),to=p.effectiveTo?new Date(p.effectiveTo):null;if(from>now||(to&&now>=to))return;const key=String(p.productUnitId)+'|'+String(p.priceType||'SELL');const old=activePrices[key];if(!old||new Date(old.effectiveFrom||0)<from)activePrices[key]=p;});
  const catalog=Object.keys(byProduct).map(productId=>{const p=byProduct[productId];const sellable=(unitsByProduct[productId]||[]).map(u=>{const price=activePrices[String(u.productUnitId)+'|SELL'];const factor=Number(u.conversionToBase);if(!price||!Number.isFinite(Number(price.price))||Number(price.price)<0||!Number.isFinite(factor)||factor<=0)return null;return{unitId:String(u.productUnitId),name:String(u.unitName||u.unitCode||''),symbol:String(u.unitCode||''),conversionFactor:factor,price:Number(price.price),priceId:String(price.priceId)};}).filter(Boolean);return{productId,name:String(p.name),sku:String(p.productCode||''),stockBase:Number(stock[productId]||0),units:sellable};}).filter(x=>x.units.length);
  return{success:true,actor,products:catalog,timestamp:now.toISOString()};
}
function afGetOpenShift_(){const actor=afCurrentActor_('SELL'),rows=afRows_(afV2Spreadsheet_(),'Shift').filter(r=>String(r.actorId||'')===String(actor.userId)&&String(r.status||'').toUpperCase()==='OPEN');if(!rows.length)return{success:true,actor,shift:null};const r=rows[rows.length-1];return{success:true,actor,shift:{shiftId:String(r.shiftId),openedAt:r.openedAt||null,openingCash:Number(r.openingCash||0)}};}
function afCurrentActor_(capability){const email=String(Session.getActiveUser().getEmail()||'').trim().toLowerCase();if(!email)throw afHttpError_('AUTHENTICATION_REQUIRED','Google account identity is unavailable to the Apps Script execution context.');const rows=afRows_(afV2Spreadsheet_(),'_V2_ACCESS');const row=rows.find(r=>String(r.Email||r.email||'').trim().toLowerCase()===email&&afBool_(r.Active!=null?r.Active:r.active));if(!row)throw afHttpError_('FORBIDDEN','Google account is not authorized for Ana Farma V2.');const capabilities=String(row.Capabilities||row.capabilities||'').split(',').map(x=>x.trim()).filter(Boolean);if(capability&&capabilities.length&&!capabilities.includes(capability)&&!capabilities.includes('*'))throw afHttpError_('FORBIDDEN','Capability '+capability+' is not granted.');return{userId:String(row.UserId||row.userId||email),email,role:String(row.Role||row.role||''),capabilities};}
function afRows_(ss,name){const sh=ss.getSheetByName(name);if(!sh||sh.getLastRow()<2)return[];const values=sh.getDataRange().getValues(),headers=values[0].map(String);return values.slice(1).filter(r=>r.some(v=>v!==''&&v!==null)).map(r=>{const o={};headers.forEach((h,i)=>o[h]=r[i]);return o;});}
function afParseBody_(e){if(!e||!e.postData||!e.postData.contents)throw afHttpError_('INVALID_REQUEST','Request body is required.');let body;try{body=JSON.parse(e.postData.contents);}catch(_){throw afHttpError_('INVALID_JSON','Request body must be valid JSON.');}if(!body||typeof body!=='object')throw afHttpError_('INVALID_REQUEST','Request body must be an object.');return body;}
function afBool_(v){return v===true||String(v).toUpperCase()==='TRUE'||String(v)==='1';}
function afHttpError_(code,message){return Object.assign(new Error(message),{code,httpStatus:code==='FORBIDDEN'?403:code==='AUTHENTICATION_REQUIRED'?401:400});}
function afJson_(payload){return ContentService.createTextOutput(JSON.stringify(payload)).setMimeType(ContentService.MimeType.JSON);}
function afError_(error){return afJson_({success:false,error:error.code||'INTERNAL_ERROR',message:error.message||'Internal error.'});}
