export class TransactionError extends Error {
  constructor(code, message = code, details = null) {
    super(message); this.name = 'TransactionError'; this.code = code; this.details = details;
  }
}

export const TransactionCodes = Object.freeze({
  INVALID_REQUEST: 'INVALID_REQUEST', INVALID_REQUEST_ID: 'INVALID_REQUEST_ID', REQUEST_IN_PROGRESS: 'REQUEST_IN_PROGRESS',
  REQUEST_PAYLOAD_MISMATCH: 'REQUEST_PAYLOAD_MISMATCH', REQUEST_RECOVERY_REQUIRED: 'REQUEST_RECOVERY_REQUIRED', REQUEST_FAILED: 'REQUEST_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED', SHIFT_REQUIRED: 'SHIFT_REQUIRED', PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND', UNIT_NOT_SELLABLE: 'UNIT_NOT_SELLABLE',
  PRICE_NOT_AVAILABLE: 'PRICE_NOT_AVAILABLE', INVALID_QUANTITY: 'INVALID_QUANTITY', INVALID_MONEY: 'INVALID_MONEY',
  INVALID_DISCOUNT: 'INVALID_DISCOUNT', INVALID_TAX: 'INVALID_TAX', INVALID_PAYMENT: 'INVALID_PAYMENT', INSUFFICIENT_PAYMENT: 'INSUFFICIENT_PAYMENT',
  STOCK_INSUFFICIENT: 'STOCK_INSUFFICIENT', TRANSACTION_CONFLICT: 'TRANSACTION_CONFLICT', COMMIT_FAILED: 'COMMIT_FAILED',
  TRANSACTION_RECOVERY_REQUIRED: 'TRANSACTION_RECOVERY_REQUIRED'
});
